version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: medicine-cal-db
    restart: always
    environment:
      POSTGRES_DB: medicine_cal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .db/postgres_data:/var/lib/postgresql/data
    ports:
      - 5443:5432


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medicine-cal-app
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/medicine_cal?schema=public
      NEXTAUTH_SECRET: UQ3lOFK9x1brurCmJblOIIvk9SG0vC2ercModRmbqwc=
      NEXTAUTH_URL: https://medicine-calendar.footgolflegends.com
      VIRTUAL_HOST: medicine-calendar.footgolflegends.com
      CERT_NAME: footgolflegends.com
      VIRTUAL_PORT: 3000
    depends_on:
      - postgres
    networks:
      - default
      - proxy


volumes:
  postgres_data:

networks:
  proxy:
    name: webproxy
    external: true